//! OTLP protobuf encoding — turns the InternalEnvelope mapping result
//! (ExportTraceServiceRequest) into wire bytes. OTLP/HTTP protobuf is uncompressed by default (no zstd).

use crate::CodecError;
use prost::Message;

// Code generated by prost encodes cross-package references as `super::super::...`
// (relative paths based on the dotted package path). E.g. opentelemetry.proto.trace.v1
// references opentelemetry.proto.common.v1 as `super::super::common::v1::KeyValue` — this
// only holds when the actual module tree is exactly isomorphic to the dotted package
// path (opentelemetry::proto::{common,resource,trace}::v1). So the code below mirrors
// the package path verbatim for the includes, then re-exports as
// `otlp_pb::{common,resource,trace,trace_service}` for convenience.
pub mod otlp_pb {
    pub mod opentelemetry {
        pub mod proto {
            pub mod common {
                pub mod v1 {
                    include!(concat!(
                        env!("OUT_DIR"),
                        "/opentelemetry.proto.common.v1.rs"
                    ));
                }
            }
            pub mod resource {
                pub mod v1 {
                    include!(concat!(
                        env!("OUT_DIR"),
                        "/opentelemetry.proto.resource.v1.rs"
                    ));
                }
            }
            pub mod trace {
                pub mod v1 {
                    include!(concat!(env!("OUT_DIR"), "/opentelemetry.proto.trace.v1.rs"));
                }
            }
            pub mod collector {
                pub mod trace {
                    pub mod v1 {
                        include!(concat!(
                            env!("OUT_DIR"),
                            "/opentelemetry.proto.collector.trace.v1.rs"
                        ));
                    }
                }
            }
        }
    }

    pub use opentelemetry::proto::collector::trace::v1 as trace_service;
    pub use opentelemetry::proto::common::v1 as common;
    pub use opentelemetry::proto::resource::v1 as resource;
    pub use opentelemetry::proto::trace::v1 as trace;
}

pub fn encode_traces(
    req: &otlp_pb::trace_service::ExportTraceServiceRequest,
) -> Result<Vec<u8>, CodecError> {
    Ok(req.encode_to_vec())
}

pub fn decode_traces(
    data: &[u8],
) -> Result<otlp_pb::trace_service::ExportTraceServiceRequest, CodecError> {
    otlp_pb::trace_service::ExportTraceServiceRequest::decode(data).map_err(CodecError::Decode)
}

#[cfg(test)]
mod tests {
    use super::otlp_pb::trace::{ResourceSpans, ScopeSpans, Span};
    use super::otlp_pb::trace_service::ExportTraceServiceRequest;
    use super::*;

    fn sample() -> ExportTraceServiceRequest {
        let span = Span {
            trace_id: vec![1u8; 16],
            span_id: vec![2u8; 8],
            name: "HTTP POST /v1/chat".into(),
            ..Default::default()
        };
        ExportTraceServiceRequest {
            resource_spans: vec![ResourceSpans {
                scope_spans: vec![ScopeSpans {
                    spans: vec![span],
                    ..Default::default()
                }],
                ..Default::default()
            }],
        }
    }

    #[test]
    fn roundtrip() {
        let req = sample();
        let bytes = encode_traces(&req).unwrap();
        let back = decode_traces(&bytes).unwrap();
        assert_eq!(back, req);
    }

    #[test]
    fn deterministic() {
        let req = sample();
        assert_eq!(encode_traces(&req).unwrap(), encode_traces(&req).unwrap());
    }

    #[test]
    fn empty_request() {
        let req = ExportTraceServiceRequest::default();
        let bytes = encode_traces(&req).unwrap();
        assert!(decode_traces(&bytes).unwrap().resource_spans.is_empty());
    }
}
